[package]
name = "doom_fire_fx"
version = "0.1.0"
authors = ["Chris Paterson <cjpaterson.3@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]
